Mostly format changes to some config files

diff --git a/bin/lib/androidsync b/bin/lib/androidsync
--- a/bin/lib/androidsync
+++ b/bin/lib/androidsync
@@ -1,20 +1,23 @@
 #!/bin/bash
-# Sync Files from Linux to android
- 
+# Sync Files from Linux to Android
+
+FTP_SERVER="192.168.1.3"
+FTP_PORT="2121"
+
 screenshots() {
    cd ~/MediaHub/screenshots/
-   lftp ftp://192.168.1.3:2121 -e "
-   cd MediaHub;
+   lftp ftp://${FTP_SERVER}:${FTP_PORT} -e "
+   cd Pictures;
    mirror -R --use-pget-n=5 --parallel=5 --delete-first --only-missing --no-recursion --no-perms;
-   bye"   
+   bye" || echo "Screenshots sync failed!"
 }
 
 music() {
    cd ~/Music/2015-2022/
-   lftp ftp://192.168.1.3:2121 -e "
+   lftp ftp://${FTP_SERVER}:${FTP_PORT} -e "
    cd Music;
-   mirror -R --use-pget-n=5 --parallel=5 --no-recursion --delete-first --ignore-time --no-perms -v;
-   bye"
+   mirror -R --use-pget-n=5 --parallel=5 --no-recursion --delete-first --no-perms -v;
+   bye" || echo "Music sync failed!"
 }
 
 PS3='Please enter your number choice: '
@@ -31,8 +34,8 @@ do
         "Quit")
             break
             ;;
-        *) echo "invalid option $REPLY";;
+        *) echo "Invalid option $REPLY";;
     esac
-read -p "Press Enter to continue"
-break
+    read -p "Press Enter to continue"
+    break
 done
